### ISSUE TITLE
Add flatten() method

### ISSUE THREAD

**Issue by albshady** [VolodymyrBor/iter_model#27]
Hi! I've been using your library for some time and it's been incredibly helpful! I have a suggestion to add a `.flatten()` method to `SyncIter` and `AsyncIter`. These methods could work similarly to the `flatten` function in `more-itertools`, which is documented [here](https://more-itertools.readthedocs.io/en/stable/api.html#more_itertools.flatten).

I often find myself dealing with `Iter[Iterable[T]]` structures and needing to transform them into `Iter[T]`. Having a `flatten()` method would make it so much more straightforward. I'd love to get your thoughts on this. If it sounds like a good addition, I'm happy to contribute a PR.

Thanks for your work on this library!

**Comment by VolodymyrBor** [comment]
Hello,
yes, that would be a useful new feature.

Prepare a PR 🙏. if not, I can prepare it this weekend.

Glad to see that someone is interested in this library, it inspires me to return to it

**Comment by VolodymyrBor** [comment]
@albshady you can check out the new relese: [2.3.0](https://github.com/VolodymyrBor/iter_model/releases/tag/v2.3.0) 🎉
